# Generated by Django 5.2.9 on 2026-02-04 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_donor_status_alter_doctor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.recipient'),
        ),
    ]
