# Generated by Django 5.2.9 on 2026-02-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appointment_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
